language: node_js

node_js:
  - 12

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      script: npm run test
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
