language: node_js

node_js:
  - 8

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      script: npm run test
    - stage: release
      script: npm run semantic-release
